name: Run on push to main

on:
  push:
    branches:
      - main

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest

    env:
      S3_BUCKET_BETA: ${{ secrets.S3_BUCKET_BETA }}
      S3_BUCKET_PROD: ${{ secrets.S3_BUCKET_PROD }}
      DEPLOY_ENV: beta

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 jinja2


      - name: Run script
        run: python process_prompt.py
